### ISSUE TITLE
DeployForTenantTags task parameter is misspelled as DeplyForTentantTags

### ISSUE THREAD

**Issue by ArturDorochowicz** [OctopusDeploy/OctoTFS#105]
It's misspelled in the following two places.
https://github.com/OctopusDeploy/OctoTFS/blob/402ec236daf4a046f3ad589ae2674ecc7fe5553c/source/tasks/Promote/index.ts#L22
https://github.com/OctopusDeploy/OctoTFS/blob/402ec236daf4a046f3ad589ae2674ecc7fe5553c/source/tasks/Deploy/index.ts#L20

**Comment by mcasperson** [comment]
Hi @ArturDorochowicz, thanks for the report. We'll fix this up with https://github.com/OctopusDeploy/OctoTFS/pull/106.
