### ISSUE TITLE
VSTS reporting errors when including changesets or work items

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/OctoTFS#107]
We've got a number of reports that VSTS is failing on the create release step when changesets or work items are enabled.

Some examples are:

![image](https://user-images.githubusercontent.com/160104/46049799-b3fe7e00-c173-11e8-80a1-4cab6d681794.png)

```
2018-09-24T18:00:04.2415923Z ##[section]Starting: Create Octopus Release: Smart_Service.ERollOff
2018-09-24T18:00:04.2422891Z ==============================================================================
2018-09-24T18:00:04.2423067Z Task : Create Octopus Release
2018-09-24T18:00:04.2423204Z Description : Create a Release in Octopus Deploy
2018-09-24T18:00:04.2423363Z Version : 2.0.135
2018-09-24T18:00:04.2423605Z Author : Octopus Deploy
2018-09-24T18:00:04.2423769Z Help : Version: 2.0.135. More Information
2018-09-24T18:00:04.2423988Z ==============================================================================
2018-09-24T18:00:08.0667668Z Environment = TfsVersionControl
2018-09-24T18:00:08.0668360Z Comments = True, WorkItems = True
2018-09-24T18:00:08.5956383Z ##[error]The remote server returned an error: (400) Bad Request.
2018-09-24T18:00:08.6090877Z ##[section]Finishing: Create Octopus Release:
```

Some have reported that disabling the changeset or workitems options in the create release step can be used as a workaround.

**Comment by mcasperson** [comment]
This appears to be an issue in the `getLinkedReleaseNotes()` function.

We see the output from these log messages:

```
    console.log(`Environment = ${environment.buildRepositoryProvider}`);
    console.log(`Comments = ${includeComments}, WorkItems = ${ includeWorkItems}`);
```

It then calls:

```
const changes = await client.getBuildApi()
        .then(x => x.getBuildChanges(environment.projectName, environment.buildId));
```

After this line we would expect to see another console log output, but in the output above the we don't, which indicates `const changes = await client.getBuildApi().then(x => x.getBuildChanges(environment.projectName, environment.buildId));` is the cause of the issue.

**Comment by mcasperson** [comment]
https://github.com/Microsoft/azure-devops-node-api/blob/a9304ac939ca9b3d09963dfbb98cb69cf9499685/api/BuildApi.ts#L844 Seems to be the offending code (or at least it was in when the library was called vso-node-api and version 6.5.0)

**Comment by mcasperson** [comment]
Version 3.0.171 of the plugin has been release with the latest libraries, which includes updates to the getBuildChanges() function. The contents of the getLinkedReleaseNotes() function is now in a try catch block so a failed attempt to get the change set doesn't block the creation of a release.

**Comment by brenkehoe** [comment]
I have updated from 2.* to 3.* version of the Create Release Tak to try and fix this issue. The problem i now see is
![image](https://user-images.githubusercontent.com/786458/46072896-684fd280-c17b-11e8-879f-e1963cae7672.png)
I also notice in the settings the channel list never shows any of the channels for the project and i have to type the name by hand.
Any ideas what could be wrong here?
Octopus Server Version 2018.5.2

**Comment by mcasperson** [comment]
The previous release didn't actually include the updated libraries or exception catching, so wouldn't have provided any change. Version 3.0.172 has been deployed with the updates, and should catch the failed network requests.

**Comment by mcasperson** [comment]
@brenkehoe

>  I also notice in the settings the channel list never shows any of the channels for the project and I have to type the name by hand.

This will be a separate issue to the errors being reported during release creation. An issue has been created at https://github.com/OctopusDeploy/OctoTFS/issues/109 for this.

**Comment by brenkehoe** [comment]
Thanks, @mcasperton, for now, I have disabled the comments and work items and it appears to be working apart from Octopus.Release.Number in out email template now shows as NaN.

Also from more testing, any build with comment and workitem appears to work when the 2 options are selected. But subsequent manual builds fail with the Duplicate Key error.

**Comment by mcasperson** [comment]
@brenkehoe If there are issues in Octopus steps (it sounds like the issue is with the email step in Octopus?) once the release is created, can I get you to submit it to the support channels at https://octopus.com/support. That will then be directed to the appropriate support team.

**Comment by kh1rfan08** [comment]
this issue has came back to life in our VSTS setup, i've disable the two steps as a workaround for now, just thought i'd drop in for someone to check on the try catch block meant to save this error from happening in a not so silent way
