### ISSUE TITLE
Build Repository Provider constant is different

### ISSUE THREAD

**Issue by EverPresent** [OctopusDeploy/OctoTFS#11]
Hey, I just started using this and it's AWESOME!  I'm using VSO with the new build system.  I had to make one minor change to get the changeset comments and work items included in the build release notes.  The code is currently looking for the repo provider to be named "Tfvc" but after not getting these comments I did some debugging and found that my repo provider is named "TfsVersionControl".  I'm not sure why this is different but I changed the two checks to look for this constant and everything worked after that:

```
if ($env:BUILD_REPOSITORY_PROVIDER -eq "TfsVersionControl") {
    ...
}
```

**Comment by philip-reed** [comment]
Confirmed, I get the same issue using 0.2.8.
Output of `Write-Host "Provider = $env:BUILD_REPOSITORY_PROVIDER"` is `2015-08-28T11:45:25.7027166Z Environment = TfsVersionControl` using Visual Studio Online.
