### ISSUE TITLE
Timeout value is not respected by the Octopus client

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/OctoTFS#134]
You can define a timeout in the TFS steps, but when deploying a release this value is not passed to the Octopus client. For example, setting a timeout of 30 minutes will still result in a long deployment failing after 10 minutes, because the Octo.exe `--timeout` value defaults to 10 minutes.

**Comment by johnsimons** [comment]
So after some digging around, we cannot do this for the users, see https://github.com/microsoft/azure-pipelines-task-lib/issues/796.
However, it is possible to control the timeout and cancel a deployment task by supplying extra `octo` arguments, here is an example:
![image](https://user-images.githubusercontent.com/122651/135545080-11cd1110-0430-4494-9a07-93b4eeebeb43.png)

So for now I am closing this issue.
