### ISSUE TITLE
Channels are not being populated in drop down list when project name is a variable

### ISSUE THREAD

**Issue by fhanggi** [OctopusDeploy/OctoTFS#145]
Channels drop down is not being populated. The issue is that we are using a variable as the Project name e.g. $(OctoPackProjectName) then the API call just uses the variable as a string

This results in the error below
{"result":[],"statusCode":"notFound","errorMessage":"Failed to query service endpoint api: https://covtools01//api/projects/$(OctoPackProjectName)/channels. Error Message: The remote server returned an error: (404) Not Found.."}

When i select a Project Name from the drop down list the channel drop down is populated correctly.
Can you please fix this so that the variable is not used as a string in the API call?

**Comment by johnsimons** [comment]
Hi @fhanggi,

Unfortunately, we don't have the option of expanding the variable value before doing the rest API call. In other words, this is managed by Azure pipelines infrastructure and it cannot be changed.

I will close this, for now, if there are any other questions let us know.
