### ISSUE TITLE
Getting CMD.exe error: The command line is too long

### ISSUE THREAD

**Issue by fourpastmidnight** [OctopusDeploy/OctoTFS#151]
When pushing packages to the Octopus Deploy Nuget feed during the TFS build process, this plugin uses CMD.exe to execute the package push command for Octo.exe. Today, our build failed because the command was too long.

As I understand it, the maximum command line length for CMD.exe is 8191 characters.

Can this plugin use PowerShell instead to invoke the command? Or at the very least, determine the length of the command to be generated and "chunk" as appropriate to avoid these kinds of errors?

**Comment by fourpastmidnight** [comment]
OK, I'm unblocked on this--but it could still conceivably be an issue where a build produces many independent artifacts to be deployed (such as ours). In our specific case, there was an error during a previous build, and a clean of the previous build artifacts was not performed, and so 2 versions of each package were in the staging folder and subsequently were attempted to be pushed to the Octopus Deploy server.

But still, a user should not expect to run up against command-line length limitations to the extent possible.

**Comment by johnsimons** [comment]
@fourpastmidnight it seems you are unstuck, closing this for now.
