### ISSUE TITLE
Error installing extension in TFS 2017

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/OctoTFS#155]
The task.json files can not be found, and the IDs for the tasks have been duplicated. This prevents the extension from being installed in TFS 2017 (and probably elsewhere too).

The error says `The task.json file was not found in contribution tasks/CreateOctopusRelease`.

![image](https://user-images.githubusercontent.com/160104/63321618-9f673d80-c364-11e9-96d9-9946e9056585.png)

**Comment by matt-richardson** [comment]
Which version of TFS 2017 is this, @mcasperson? We no longer support TFS2017 update 1

**Comment by mcasperson** [comment]
This was TFS update 1. The error does not appear in 2017 Update 3.

**Comment by mcasperson** [comment]
I confirmed that the install works in TSF 2017 Update 2. The landing page at https://marketplace.visualstudio.com/items?itemName=octopusdeploy.octopus-deploy-build-release-tasks&ssr=false#overview says that the extensions supports TFS 2017 Update 1, so this has been corrected.

**Comment by matt-richardson** [comment]
Thanks @mcasperson - this was on #pod-brickburgs todo list.
We'll also need to update [this page](https://octopus.com/docs/packaging-applications/build-servers/tfs-azure-devops/using-octopus-extension/extension-compatibility#octopus-extension-versions) to add a new direct link to the last 3.x extension (3.0.222) that supports TFS2017 update 1

**Comment by mcasperson** [comment]
The customer reported updating to TFS 2017 Update 3 solved the issue.
