### ISSUE TITLE
Create release step is always passing the release notes file

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/OctoTFS#160]
The Create Release step implementation regressed at some point and no longer uses the checkboxes related to whether to build the release notes, it always build the file and passes it regardless of their value.

This has a knock on effect for the new release notes templates functionality in Octopus. When the release notes file is passed via octo.exe to the API it's contents override the project's release notes template, which means the templates cannot be used when the release is being created by ADO.

**Comment by thedewi** [comment]
Fixed in #161.
