### ISSUE TITLE
Allow ignoring of SSL errors when connecting to TFS/ADO

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/OctoTFS#162]
The Package Metadata step allows ignoring SSL certificate errors when pushing data to Octopus (via the Service Connection properties). However, it also needs to pull the commit/work item data back from TFS/ADO and the Node connection for that doesn't currently allow configuration for ignoring SSL errors.

We should add an option (under `Advance Options`) to specify to ignore SSL errors on the connection to TFS/ADO.

**Comment by johnsimons** [comment]
Implemented in https://github.com/OctopusDeploy/OctoTFS/pull/117
