### ISSUE TITLE
Need documentation for using OctopusMetadata with azure devops yaml

### ISSUE THREAD

**Issue by pswetz** [OctopusDeploy/OctoTFS#168]
Need documentation for using OctopusMetadata with azure devops yaml. Example usage, parameters and so on.

**Comment by johnmc-tc** [comment]
Is there any documentation AT ALL on the YAML side of things? I've spent the last 20 minutes searching and cannot, other than a few posts on Stackoverflow.

**Comment by antmeehan** [comment]
This would be very helpful. All the Octopus Deploy docs just have the classic editor style examples. I end up using the fancy editor in AzDO to generate the YAML and then paste into my existing pipeline YAML files:

![image](https://user-images.githubusercontent.com/9822503/125633614-ee2d3e60-75c1-4bed-b70c-0ff5550844a8.png)


I had wondered whether Microsoft auto-generate their [YAML snippet](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/archive-files?view=azure-devops#yaml-snippet) for the in-built tasks, but alas it all looks hand-crafted, eg: https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/includes/yaml/ArchiveFilesV2.md

**Comment by johnsimons** [comment]
We have added doco for the "Push Package Build Information to Octopus" in the https://marketplace.visualstudio.com/items?itemName=octopusdeploy.octopus-deploy-build-release-tasks

But as @antmeehan and @johnmc-tc point out, we have no doco for the yaml side of things.
The best way to go about exploring the yaml is to do what @antmeehan [refers](https://github.com/OctopusDeploy/OctoTFS/issues/168#issuecomment-879911267) to ☝️ 

At this time we have no plans to add doco for the yaml. If you feel we must have doco for yaml let us know and we can reconsider.
