### ISSUE TITLE
Not Processing Variables in Octopus Arguments...

### ISSUE THREAD

**Issue by DynConcepts** [OctopusDeploy/OctoTFS#17]
I would like to pass:  --packageversion=0.0.$(DayOfYear)$(Rev:.rr)

However, this appears to be passed the command-line as a literal without substituting the appropriate elements (to create a 4 part version number).

**Comment by DynConcepts** [comment]
It looks like this is because the task.json is specifically configured to prevent such usage. The question is WHY?

This is related to issue #18 and preventing passing in the dynamically known build number....

**Comment by Damovisa** [comment]
Hi @DynConcepts,

Firstly, apologies for the delay in responding.

I'm trying to get help from the build team regarding passing variables to parameters. They should ideally be resolved when passed to the script.

I'm not sure what you mean by your comment about the task.json being configured to prevent this, however. The parameter is simply a string that gets passed to the PowerShell script. Is there something you'd expect to see here instead?

Thanks,
Damo

**Comment by Damovisa** [comment]
Hi @DynConcepts,

I've got to the bottom of it. It appears that the `$(DayOfWeek)` and `$(Rev:.rr)` variables are only valid when specifying a build number format. In other words, they're not variables that can be used directly in step parameters.

As a workaround, you could set the Build number format in the General tab to `0.0.$(DayOfYear)$(Rev:.rr)`, then use `--packageversion=$(Build.BuildNumber)` in the Additional Octo.exe Arguments parameter. This obviously requires the build number to match your package version.

I hope this helps,
Damo

**Comment by DynConcepts** [comment]
Thanks... I was about to post the same thing. Those items are not really "variables" but are "format specifiers" that are specific to the processing of the BuildNumber. 

You are also right with the workaround, but it is "partial" an "fragile" [this is not specific to your Octopus task, but is a general condition. Having a hard dependency between the name that is displayed in the UI and the values that are used for things such as artifacts is problematic from a design [Coupling - SRP] point of view; I am working on some techniques to make this better (if I am successful, I will post). Again, this is not specific to your task.
