### ISSUE TITLE
Links to workitems are incorrect when not in the same project

### ISSUE THREAD

**Issue by veccsolutions** [OctopusDeploy/OctoTFS#179]
When linked work items in the builds are in a different project from the one that the build is in the links in the release notes are incorrect.

**Comment by danefalvo** [comment]
Hi veccsolutions,

Thank you very much for bringing this issue to our attention. I have been investigating to see if the issue still exists in the latest version of Octopus and although the issue isn't identical to what you are describing, there is still definitely some improvements that could be made when dealing with out-of-scope linked Work Items. 

Can I please get a little bit more information about the issue you're seeing? 

What version of Octopus Deploy are you using?
What version of TFS are you running?

When testing with the cloud version with Azure DevOps, the Commit Message completely disappears within the Work Items section of Releases. Is that different to what you are seeing on your Octopus Server? If you can, please provide an example of one of the incorrect links that gets created.

Once you get back to me with a little more detail, I should be able to update this ticket (https://github.com/OctopusDeploy/Issues/issues/6421) with the additional information. 

Thank you so much for your time.

Regards,

Dane

**Comment by johnsimons** [comment]
User never got back, and it seems the issue is the actual integration in the Server - https://github.com/OctopusDeploy/AzureDevOpsIssueTracker/issues/19
