### ISSUE TITLE
Not deploying the build just produced...

### ISSUE THREAD

**Issue by DynConcepts** [OctopusDeploy/OctoTFS#18]
It appears that this task will always deploy the highest revision in the repository...This is fatal with concurrent development. Let consider 1.1.x.x and 1.2.y.y are both being developed. A new build of 1.1 creates a deploy that uses the highest published (Which will be 1.2!!!)

**Comment by Damovisa** [comment]
Hi @DynConcepts,

This issue should be largely solved by the new [Channels](http://docs.octopusdeploy.com/display/OD/Channels) feature. You can define a different channel for `1.1.*` and `1.2.*`, then provide `--channel=channelname` as an additional argument.

Note that this doesn't take into account #17 - I'm still looking at passing variables.

Thanks,
Damo
