### ISSUE TITLE
Add support for pushing a nupkg to OD as a discrete build step

### ISSUE THREAD

**Issue by roryprimrose** [OctopusDeploy/OctoTFS#19]
I use the project configuration in OD to create the release. What I'm after is the ability to publish the package to OD after tests have passed. For example:

Run msbuild
Run tests
Publish package

Currently the only option appears to be to publish as part of OctoPack in MsBuild. The downside of this is that it publishes the packages for deployment even if the tests indicate a busted build.

**Comment by Damovisa** [comment]
Hi @roryprimrose,

You should be able to use the out-of-the-box `NuGet Packager` and `NuGet Publisher` build tasks to do the packaging and publishing if you don't want to use OctoPack.

If you need OctoPack to handle web projects, you can still use OctoPack to package, but then use the `NuGet Publisher` step to push it to Octopus.

Thanks,
Damo

**Comment by Damovisa** [comment]
No need to fix. NuGet publish steps are included in the box.

https://msdn.microsoft.com/en-us/Library/vs/alm/Build/steps/package/nuget-publisher
