### ISSUE TITLE
Uncomplete error 'VS403685: This widget configuration reported an error: "'

### ISSUE THREAD

**Issue by weijia-ai** [OctopusDeploy/OctoTFS#193]
Hi, when I was adding widget to ADO dashboard I got this uncompleted error message:  'VS403685: This widget configuration reported an error: "'
The error message is literally like that, see image:
![image](https://user-images.githubusercontent.com/52427362/109723465-f86f7e80-7b62-11eb-9a92-7ed2f1609280.png)
 
I can see this error in almost all widget but some widget can render a table/matrix fine but some others were having problem loading it.
I also attached my console screenshot below.
![image](https://user-images.githubusercontent.com/52427362/109723612-2d7bd100-7b63-11eb-8a6c-232eef849e5d.png)

So the widget looks empty even though I provided a valid query and can get the result somewhere else.
Here is what the widget looks like:
![image](https://user-images.githubusercontent.com/52427362/109723743-5dc36f80-7b63-11eb-9560-ec7eea5656ed.png)

**Comment by johnsimons** [comment]
Wrong repo, our widget is called "Octopus Deploy Status"
