### ISSUE TITLE
OctoTFS: Octopus Server returns 500s on steps with Project Group/Project dropdown boxes

### ISSUE THREAD

**Issue by pstephenson02** [OctopusDeploy/OctoTFS#194]
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

After selecting a space, when you then try to click the Project or Project Group dropdowns, Octopus returns a `500: Variable with name SpaceId could not be found for the given endpoint` - Neither the projects nor project groups are returned or populated into the corresponding dropdowns.

## What I expected to happen

Octopus would properly return the Projects / Project groups

## Steps to reproduce

1. Create a project in TFS
2. Click 'Add Task' and find Create Octopus Release
3. Select an Octopus Server and Space
4. Select Project Group or Project and note the projects are not populated.

### Screen capture

![tfsbug](https://user-images.githubusercontent.com/6306934/95797443-685c9580-0ca4-11eb-89d7-ddb68d44459f.gif)

### Log exerpt

** See Screen capture above for log.

## Affected versions

Confirmed as an issue on TFS 2017 update 3. Tested as working on Azure DevOps 2019 on-prem, as well as AzDO online.
 
## Workarounds

The space selector does not exhibit any issues, all subsequent controls that rely on the space selection will fail. 
The project group is not required, each of the other required fields such as `Project` or `Environment` can be supplied with either the name or the id, such as `Projects-1` or `Environments-1`

## Links

https://octopususergroup.slack.com/archives/C6UGLUWMQ/p1602177188201800
https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1602270160233700
https://trello.com/c/F8jOKHr5/3799-issue-with-tfs-integration

**Comment by johnsimons** [comment]
This is a bug with that particular version, please update to latest versions
