### ISSUE TITLE
BuildInformation task does not detect all changes

### ISSUE THREAD

**Issue by resnikb** [OctopusDeploy/OctoTFS#195]
Hi,
I've noticed that some commit messages (containing Jira issue numbers) are missing from Octopus build information. We use the BuildInformation task to generate and push the information, and it seems that only the top 50 commit messages are included.

I have tested this locally, and it seems that `getBuildChanges` method from `azure-devops-node-api/BuildApi` returns only top 50 by default (some of our builds have a lot more than that). This may be an undocumented default of the underlying Azure DevOps API, however it would be good if the BuildInformation task would get all changes, perhaps through the use of `top` parameter to increase the number of changes returned?

In my test, I explicitly specified the `top: 1000` parameter, and verified that all expected changes are returned. There doesn't seem to be a way to get the continuation token from the response though.

**Comment by johnsimons** [comment]
Fixed in https://github.com/OctopusDeploy/OctoTFS/pull/196
