### ISSUE TITLE
Release Notes are conditionally empty

### ISSUE THREAD

**Issue by paulgelardi** [OctopusDeploy/OctoTFS#204]
When using the task to Create a Release, if none of [ChangesetCommentReleaseNotes, WorkItemReleaseNotes, CustomReleaseNotes] are set, Release Notes is competely empty.

The generateReleaseNotesContent method always generates some high level information about what created the release, such as the build, repository, team project, etc.  
https://github.com/OctopusDeploy/OctoTFS/blob/b29c0a58c18292736ba5c1e8169ea042c4b2b64a/source/tasks/Utils/environment.ts#L58 (see lines 59-70). This logic correctly handles null checks for all of its inputs, and will generate useful output even if all of it's inputs are null/empty.

However, the logic for creating these release notes at all requires one of the above parameters to be set to even get invoked.
https://github.com/OctopusDeploy/OctoTFS/blob/master/source/tasks/CreateOctopusRelease/CreateOctopusReleaseV4/index.ts#L44

There is no way to include this high level information in the release notes without also including changeset comments, workitem information, or custom release notes.  I feel this information should be included every time, even if none of these parameters are set.

**Comment by paulgelardi** [comment]
I think the fix is as simple as removing this entire if statement.
https://github.com/OctopusDeploy/OctoTFS/blob/master/source/tasks/CreateOctopusRelease/CreateOctopusReleaseV4/index.ts#L44

I'd be happy to whip up a PR containing this change if there's agreement that it's a good change.

**Comment by slewis74** [comment]
[This change](https://github.com/OctopusDeploy/OctoTFS/commit/253f7aef284afb934022935c267c663cf7b7cd0d#diff-20b9991426649ee42b09ed91e460a4d0dbd75b34c412f761273ece0b495cd4dc) was made quite specifically when we introduced the new [Build Information](https://g.octopushq.com/BuildInformation) and [Release Notes templates](https://g.octopushq.com/ReleaseNotesTemplate) features. If the Create Release task tries to include release notes using the old method it will [override the new features](https://github.com/OctopusDeploy/OctoTFS/pull/161), but we had to leave it in here for backward compatibility at the time.
