### ISSUE TITLE
API key in the logs

### ISSUE THREAD

**Issue by roryprimrose** [OctopusDeploy/OctoTFS#21]
Hi guys,

VSTS does a great job with hiding credentials with service configuration. The logs from the powershell display these api keys in clear text however.

**Comment by Damovisa** [comment]
Hi Rory,

Can you include a screenshot or something? When I do it, the API key gets hidden in the output...

Thanks,
Damo

**Comment by roryprimrose** [comment]
Ah, my bad. It is the nuget publish task that does this. I'll raise the issue with them.
