### ISSUE TITLE
Remove ability from doing the deployment from "Create Release" task

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/OctoTFS#225]
Create Release should be just about creating a release. 
If a deployment is required, the "Deploy" task should be used.

Sometimes, when Octopus auto assigns the release number we need this value to be set as an output variable so it can be used in subsequent "deploy" or "promote" tasks.

**Comment by slewis74** [comment]
The Octopus CLI is already [emitting an output variable](https://github.com/OctopusDeploy/OctopusCLI/blob/main/source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs#L197) that contains the release version, which could be used in a subsequent DeployRelease step.

**Comment by johnsimons** [comment]
@slewis74 looking into the impl code of OtopusCLI, it doesn't look like the syntax output from the CLI is in the correct format for Azure DEVOPS to understand.

Azure DevOps expects something like `##vso[task.setvariable variable=myOutputJobVar;isoutput=true]this is the same job too`, see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=bash

This is the output we are getting in our tests:
![image](https://user-images.githubusercontent.com/122651/159389639-dd8009e4-0cc8-485d-b7db-c5a1fc0be7b8.png)
which looks very much TeamCity syntax 😞

**Comment by benPearce1** [comment]
This has been implemented in v6 of the create release step.
