### ISSUE TITLE
Remove Task, "Package Application for Octopus"

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/OctoTFS#226]
The task entitled, "Package Application for Octopus" or "OctopusPack" packages an application into a NuGet package or a ZIP archive.

This task was created and supported through the Octopus CLI back when Octopus Deploy only supported NuGet packages.
At that time, it was difficult to package applications as NuGet packages. Later, we added support for ZIP archives, tarballs, etc. Eventually, the need/use for this task diminished due to alternatives like `dotnet pack`.

This issue proposes removing this task from the plugin.

**Comment by johnsimons** [comment]
This issue was actioned as part of https://github.com/OctopusDeploy/OctoTFS/pull/223

**Comment by buckleyGI** [comment]
Hi John. A version of the migration that show the yaml involved would be quite helpful.
I'm starting such a migration now, and these screenshots certainly help, but I think a good part of people use yaml.

**Comment by johnsimons** [comment]
@buckleyGI I think the only trickier part is to ensure the filename contains the version, eg `MyPackage.2.5.6.zip` see https://octopus.com/docs/packaging-applications#package-id for more info.
