### ISSUE TITLE
Allow users to add Release Notes as part of CreateRelease task

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/OctoTFS#227]
In V3 we used to support adding "custom release notes"
<img width="288" alt="image" src="https://user-images.githubusercontent.com/122651/159381789-16c2f900-5b8e-46d5-ac31-1c52a27d2110.png">

Then in V4 we decided to deprecate that feature in favour of the "Build Information" task
<img width="254" alt="image" src="https://user-images.githubusercontent.com/122651/159381852-8c551043-c83d-4140-a4be-cad08fd103ab.png">

However Build Information is not for everyone, and some customers want to just add "Release Notes" to a release in textual format.

So in V5 we are removing the "ChangeSets and Workitems" but leaving the text field to add Release notes.
<img width="273" alt="image" src="https://user-images.githubusercontent.com/122651/159381973-458360ea-3cdd-4f04-9904-aa41c9ea4619.png">

This means users can just type their release notes in the field to be included in the release.

This means users need to make a choice about release notes, they can include them manually, or use the "Build Information" task.

**Comment by johnsimons** [comment]
@slewis74 before we were merging both the "Build Information" + custom release notes as a single "release notes".
This change will prevent users from doing this, do you see this as a problem?

**Comment by slewis74** [comment]
Yeah, in the older code in the plugin it was doing some merging and plugging the result into the ReleaseNotes field for the release. The Release templates in Octopus (which can use Build Information) are separate and kick in if the ReleaseNotes on the release are left blank. So I think just leaving the release notes text field in the step here is fine.

**Comment by johnsimons** [comment]
This issue was actioned as part of https://github.com/OctopusDeploy/OctoTFS/pull/223
