### ISSUE TITLE
Overwrite mode in yaml definition does not feel right

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/OctoTFS#233]
![image](https://user-images.githubusercontent.com/122651/160723699-9757d56c-35c1-4c33-a5bc-7e7c55f6a959.png)

A few things, the options values are booleans + something else.

The autocomplete in the pipeline builder editor assumes 'true' to be boolean and hence errors, the workaround is to wrap it in quotes.
![Kapture 2022-03-30 at 09 54 14](https://user-images.githubusercontent.com/122651/160724824-03195377-a250-4a64-9d9a-f91474e6d827.gif)

It would be nice for that yaml to be something like:
`OverwriteMode: "Overwrite existing"`

**Comment by johnsimons** [comment]
@slewis74 you are looking at the UI, the yaml uses `name` from the task.json, see https://github.com/OctopusDeploy/OctoTFS/blob/a438d7771350c3551e6eada4cdfa6fb8919e7644/source/tasks/Push/PushV5/task.json#L55-L66
![image](https://user-images.githubusercontent.com/122651/160726802-85fab07c-f9a0-49f0-b70c-ea308d1fe7ec.png)

**Comment by johnsimons** [comment]
I don't think we ever thought about the yaml UX 😢

**Comment by slewis74** [comment]
👍 I had seen that, imo that is a bug/oversight and is using the wrong name

**Comment by johnsimons** [comment]
agree, but not easy to fix without breaking it
