### ISSUE TITLE
Not able to install the extension in Azure DevOps 2020

### ISSUE THREAD

**Issue by BetaVersionAnurag** [OctopusDeploy/OctoTFS#243]
Hello Team, 

We are using Azure DevOps 2020, and when I'm trying to install the latest version of this extension, it is failing with the error-  

We've encountered an error while downloading the extension. Please try again later. 

![image](https://user-images.githubusercontent.com/22211861/168593263-3972b83e-26e3-4326-be29-f427fac6c17b.png)

**Comment by jbristowe** [comment]
Hey @BetaVersionAnurag! 👋 Thanks for submitting an issue. Is this issue still ongoing? It may be due to temporary network issues.

**Comment by BetaVersionAnurag** [comment]
Yes it is still there, I have tried either by downloading the extension VSIX file and uploading the file that also fails with the error- 

**The extension package size '34193032 bytes' exceeds the maximum package size '26214400 bytes'**

**Comment by electricsysadmin** [comment]
I'm not sure if this is the right place to report this but I was not able to install this extension (version 6.0.502).

`The extension package size '34499820 bytes' exceeds the maximum package size '26214400 bytes'`

However after making the following change I was able to install the extension. It strikes me that Microsoft does not recommend making the following change. Just giving you a head's up.
https://techcommunity.microsoft.com/t5/azure-devops-blog/upload-error-the-extension-package-size-26272573-bytes-exceeds/ba-p/3048916
