### ISSUE TITLE
Extension Icon Needs Updating

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeploy/OctoTFS#273]
The icon associated with this extension is old and needs to be updated to the [latest version for Octopus Deploy](https://octopus.com/company/brand).

**Comment by benPearce1** [comment]
@jbristowe Is this still relevant? The [current logo](https://github.com/OctopusDeploy/OctoTFS/blob/main/source/extension-icon.png) that we are shipping looks the same to my untrained eye.

**Comment by benPearce1** [comment]
Completed with v6 release
