### ISSUE TITLE
Octopus-CreateRelease.ps1 fails because environment variable does not exist

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/OctoTFS#29]
Script uses `$env:BUILD_STAGINGDIRECTORY` instead of `$env:SYSTEM_ARTIFACTSDIRECTORY`.

https://github.com/OctopusDeploy/OctoTFS/blob/master/source/VSTSExtensions/OctopusBuildTasks/CreateOctopusRelease/Octopus-CreateRelease.ps1#L136

Source: http://help.octopusdeploy.com/discussions/problems/43509

**Comment by trbenning** [comment]
According to this page: https://msdn.microsoft.com/Library/vs/alm/Build/scripts/variables, $env:SYSTEM_ARTIFACTSDIRECTORY is not listed as available in Build definitions, so using it will likely just move the problem. The correct variable will need to be available in both Build and Release definitions.

**Comment by michaelnoonan** [comment]
We're going to use `$env:SYSTEM_DEFAULTWORKINGDIRECTORY` ala https://github.com/OctopusDeploy/OctoTFS/commit/d258aa3861f48a2c476d3e24f5f69b007a60138b. It just needs to be a usable temp path.

**Comment by michaelnoonan** [comment]
Currently shipped to the test environment, waiting on the VSTS Marketplace team to fix a bug which makes the Extension invisible in the Marketplace.
