### ISSUE TITLE
Bug in Get-SelectedPackages

### ISSUE THREAD

**Issue by KasperHoldum** [OctopusDeploy/OctoTFS#30]
There seem to be a bug in the above mentioned function.

The "return $packageVersions" line is located inside the for-each which creates invalid return data.

Moving the return statement outside the for-each fixed the script for our usecase where we have a seperate nuget server and thus not using the built-in one.

**Comment by Damovisa** [comment]
Thanks for reporting this @KasperHoldum! I've applied the change.

Note that we recommend using the extension if possible rather than the powershell script option. It's a lot cleaner and it's where we'll be focusing our attention :)
