### ISSUE TITLE
Extract artifacts from created release

### ISSUE THREAD

**Issue by Y29nVCt** [OctopusDeploy/OctoTFS#32]
I would like to pull back artifacts that my release/deployment creates.  Ideally, the artifacts could be filtered (wildcard or file name matching).

I have an MS Test project that is running as part of my deployment.  This generates a .xml and .trx file, both of which I would like to pass to the vNext built-in task to Publish Test Results.

**Comment by Damovisa** [comment]
Hi @Y29nVCt,

That's a tough one! There could be a way to do it, but it's definitely beyond the scope of the current build task.

The internal call to Octo.exe that gets made is fire-and-forget, so the build won't wait for your deployment to finish. However, [octo.exe has a `--waitfordeployment` flag](http://docs.octopusdeploy.com/display/OD/Creating+releases) you could use to wait until the deployment finishes.

You could write an additional build step to run afterwards that would use the Octopus API to find that completed deployment and download the artifacts.

Finally, you could use the [Publish Build Artifacts](https://msdn.microsoft.com/en-us/Library/vs/alm/Build/steps/utility/publish-build-artifacts) step to pass them back to your build, or you could also use [artifact logging commands](https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/authoring/commands.md#artifact-logging-commands) to do it inside a PowerShell script.

I hope this helps.
