### ISSUE TITLE
Output a link to the new Ocotpus build to the build summary page in VSTS

### ISSUE THREAD

**Issue by mostergaard** [OctopusDeploy/OctoTFS#34]
Great extension - just added to VSTS project, and it works like a charm.

With the old XAML based TFS build system, I had made my own extensions to the build template to create an Octopus release with the Octo.exe tool, which I guess is exactly the same as you do here. What I also did then was to add a custom element to the "build summary" output for the TFS build with a link to the newly created release on Octopus. This means that our developers can simply wait for the build to finish and then jump straight to the Octopus release from the build summary to e.g. trigger a release to the dev environment.

I'm pretty new to the new TFS Build system, but as far as I understand, you can do something similar by simply outputting a special string to the standard output starting with "##vso" - see details here: https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/authoring/commands.md

It seems that you can output a bit of markdown and that this will then be rendered on the build summary page in TFS. So the link could added that way.

This would be a great feature in the extension!

**Comment by Damovisa** [comment]
Hi @mostergaard,

That's a great idea, and it's been sitting in my backlog waiting for some more time to devote to it!

I'll no doubt get to this at some stage, but... we do accept PRs... ;)

Thanks,
Damian

**Comment by mostergaard** [comment]
Hi @Damovisa,

I've attempted at my first-ever PR for this :-)

/Morten

**Comment by Damovisa** [comment]
Hey @mostergaard,

I looked into providing a link directly to the created Release, and it turns out we were already emitting service messages for TeamCity from within `Octo.exe`. It was relatively easy to extend this to handle VSTS as well.

So sorry to say I've more or less overwritten your PR with this latest change... but if you hadn't done one, this probably wouldn't have happened for quite a while, so thanks for the push!

Can you try out the latest version and make sure the link works for you?

Thanks!
Damian

**Comment by mostergaard** [comment]
Hey Damien,

Great news - I don't care if my PR is gone, as long as we get the link into the build summary ;-)

I just tried it out, however, and it doesn't seem to work. The last few lines of output is like this:

2016-02-15T08:11:39.0228351Z Creating release...
2016-02-15T08:11:39.4774015Z Release 1.2.280 created successfully! 
2016-02-15T08:11:39.4774015Z ##[warning]Unable to find upload file from:C:\Windows\system32\88ae0015-0bd3-4885-bda1-98440f46956a.md

So it seams that the genereated MD file cannot be found by TFS Build. Maybe you need to place it in a different location? In the Powershell I wrote, I specifically placed the MD file in the same location as the Powershell script (the $PSScriptRoot variable) and that seemed to do the trick - for me at least.

Let me know if you need more details - there might be things in my builds that cause this.

Thanks
Morten

**Comment by Damovisa** [comment]
Hi @mostergaard,

Ahh, I'm guessing you're using the hosted agent? Looks like that might pose a problem. I'll start on a fix for that right now.

Thanks for reporting it!

Damian

**Comment by Damovisa** [comment]
Hi @mostergaard,

I've submitted a fix and it appears to work for the hosted build agent. Are you able to test this again?

Thanks,
Damian

**Comment by mostergaard** [comment]
Hi @Damovisa,

Great, it works now. I'm actually running an on-prem build agent - otherwise I wouldn't be able to push the release on to my on-prem Octopus server ;-) But anyhow, it works like a charm now.

Thanks :-)
/Morten
