### ISSUE TITLE
Minimum agent version Invalid

### ISSUE THREAD

**Issue by arasium** [OctopusDeploy/OctoTFS#37]
"minimumAgentVersion": "1.82.0" is wrong.

This version is provided with TFS 2015 (On premise, first version, not update 1). And this agent doesn't support some environment variables and log tools used in TfsServiceMessage (see Octo.exe).

On upload, the task will break build system.

**Comment by Damovisa** [comment]
Hi @arasium. The latest commit should have fixed this issue. (https://github.com/OctopusDeploy/OctoTFS/commit/78d71e007515516d4a4ea558e6cfaabd90ceed54)
