### ISSUE TITLE
Octopus Connection type

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/OctoTFS#41]
At the moment we use a `GenericConnection` where you need to ignore the Username field, and we use Password as API key.

We should make an `OctopusConnection` contribution as part of our Extension.

**Comment by Damovisa** [comment]
Currently being investigated in the `feature-octoendpoint` branch. This will be a breaking change, and because of the way extensions work, it will break everyone's build instantly 😟

**Comment by Damovisa** [comment]
To avoid a breaking change, we're going to include both connection types temporarily, with notes that the Generic type is deprecated.

We'll try to give people as much warning as possible before killing it properly!

**Comment by Damovisa** [comment]
Change of plans. Microsoft is intending to make it safe to deploy major version bumps. Users will be prompted to update rather than an automatic update happening.

This will be fixed with da353c4, and you'll see the changes in version 2.0.x.
