### ISSUE TITLE
Selecting correct packages

### ISSUE THREAD

**Issue by KasperHoldum** [OctopusDeploy/OctoTFS#42]
When using the TFS custom build step it doesn't select packages according to the channel rules.

If the Tag rule is 'Dev.*' it should only select packages that fit this rule when creating the release.

Is there any way to make it obey these rules?

**Comment by Damovisa** [comment]
Hi @KasperHoldum, can you confirm this is no longer an issue? We've since updated the embedded `octo.exe` which should fix that issue.

**Comment by KasperHoldum** [comment]
Yup, this appear to have been fixed.
