### ISSUE TITLE
(401) Unauthorized when trying to create release in on-premise TFS 2015

### ISSUE THREAD

**Issue by benscobie** [OctopusDeploy/OctoTFS#46]
We recently upgraded our Octopus extension from 0.6.14 to 1.0.1 and we have run into trouble creating a release when "Include Changeset Comments" is turned on. Looking over the code I'm guessing that the changes API request is failing:
Environment = TfsVersionControl
Comments = True, WorkItems = False
##[error]The remote server returned an error: (401) Unauthorized.

This is how the task is set up:
![octobug](https://cloud.githubusercontent.com/assets/944312/15038714/17d93780-129e-11e6-8965-c9b711081e15.PNG)

We're running TFS 2015 Update 2

If you need any more information let me know.

**Comment by philip-reed** [comment]
I have just encountered this also.
On Prem Build server using V1.01 of the OctopusCreateRelease script

**Comment by philip-reed** [comment]
I've done this as a temporary work around:

1. On the build server browse to [drive]\BuildAgents\tasks\OctopusCreateRelease
2. Delete the folder 1.0.1
3. Copy 0.6.14 and rename it to 1.0.1

This effectively rolls back to the previous version and stops the latest version (currently 1.0.1) from being redeployed.
When the fix comes out, presumably it will have a new version number, so you shouldn't have to do anything to undo this work around. But if you do, just delete the 1.0.1 folder again and it will be redeployed from the VSTS Marketplace.

**Comment by baronmor** [comment]
Just run into the same error on our VSTS release

**Comment by benscobie** [comment]
This is fixed in the latest version available on the marketplace although the changes don't seem to have been committed here yet.
