### ISSUE TITLE
RTM is here

### ISSUE THREAD

**Issue by adotout** [OctopusDeploy/OctoTFS#5]
Is there a way to hack this into the on-premises TFS that was released today? It seems like custom tasks still aren't fully supported, but it would be nice to test this out now.

**Comment by moppa** [comment]
Hi, You are able to upload the custom task using https://github.com/Microsoft/tfs-cli

**Comment by mattbrooks2010** [comment]
@adotout I've installed this into on-premise TFS 2015 using the CLI tool above. One thing worth pointing out is that the tool currently only supports basic auth, which I had to enable at the IIS level.

**Comment by Damovisa** [comment]
Closing this issue - you can now install extensions to TFS 2015 Update 2 and above.
