### ISSUE TITLE
Task log is not presented in TFS build console

### ISSUE THREAD

**Issue by wiruzman** [OctopusDeploy/OctoTFS#52]
Hi,

We use OctoTFS to create and deploy the packages which is created by msbuild. When the deployment is started, the build console in TFS only shows:

> 2016-06-06T12:15:57.8201301Z GET http://our.url/api/tasks/ServerTasks-11927
> 2016-06-06T12:15:57.8670232Z GET http://our-url/api/tasks/ServerTasks-11927/details

in the end and keeps repeating.

When I use octo.exe and trigger the deploy manually I get a lot of logging stuff like in the powershell window:

> Success: Acquire packages
> Info       Acquiring packages
> Info       Making a list of packages to download
> Info       Downloading package My.Package version 1.0.9-Develop058 from feed: http://our.nuget.url/OctopusNugetServer/nuget'
> Info       All packages have been acquired

and much more.

We have tried using --progress and --debug, but no luck in TFS.

Is this a bug or just something we have not activated?

**Comment by Dalmirog** [comment]
See source ticket: http://help.octopusdeploy.com/discussions/problems/46255

**Comment by Damovisa** [comment]
Closing issue as related GitHub Issue (https://github.com/OctopusDeploy/Issues/issues/2577) is closed.
