### ISSUE TITLE
Create Release task grabs highest package version, not one just made

### ISSUE THREAD

**Issue by bzbetty** [OctopusDeploy/OctoTFS#56]
Would be nice if there was an easy way to create a release for the package we just made with the package application task, even if it has a lower version number than what the latest is in octopus.

**Comment by MJRichardson** [comment]
In the "Additional Arguments" field you can supply a `--package` argument.  See the [Octo.exe documentation](http://docs.octopusdeploy.com/display/OD/Creating+releases) for details.

We may add a UI field for this at some point.

**Comment by Damovisa** [comment]
Closing. Adding a `--package` argument is the current way to do this.
