### ISSUE TITLE
Push packages - support pattern/minimatch for nupkg file(s)

### ISSUE THREAD

**Issue by DavidDeSloovere** [OctopusDeploy/OctoTFS#58]
Push packages only supports an exact path to the nupkg file (or files).
Support for pattern/minimatch would be very usefull because then you don't need to specify every nupkg file, with the correct path, and the correct version number.

I would use this:
`$(build.sourcesdirectory)\**\octopacked\*.nupkg`

Looks like the VSO Tasks lib already has something for this included.
https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/VstsTaskSdk/FindFunctions.ps1

**Comment by mud5150** [comment]
Hey David, I [created a pr](https://github.com/OctopusDeploy/OctoTFS/pull/59) for this a while ago so it's sort of in there but not implemented exactly how you suggested. Good catch on the task lib. I think it should be updated to use this as the behavior would be closer to what's expected. Do you want to put in a pr? If not I may get to at some point.

**Comment by DavidDeSloovere** [comment]
I'll see what I can do.

**Comment by kevinkuszyk** [comment]
Hi All,

What's the status on this?  Has it made it into the latest version of the extension (1.2.59)?

**Comment by Dalmirog** [comment]
Hi @kevinkuszyk - The PR from @mud5150 was [merged a while ago](https://github.com/OctopusDeploy/OctoTFS/issues/59) and should be on the latest version. 

Have you tried it and found it didn't work? If you have, this is the right thread to let everyone know :)

**Comment by kevinkuszyk** [comment]
Yes, I tried it earlier in the week and it didn't work.  I'll try to repro it again next week and post a screenshot.

**Comment by kevinkuszyk** [comment]
Ok, so I tried it again tonight and it's not working.  Here's some screen shots from a sample project which repros the issue:

Here is the step to copy my build artifacts:

![image](https://cloud.githubusercontent.com/assets/2734580/18451568/69589518-792f-11e6-8de4-51979b946fea.png)

And this is the push to Octopus step:

**Comment by kevinkuszyk** [comment]
Ok, so I tried it again tonight and it's not working.  Here's some screen shots from a sample project which repros the issue:

Here is the step to copy my build artifacts:

![image](https://cloud.githubusercontent.com/assets/2734580/18451568/69589518-792f-11e6-8de4-51979b946fea.png)

And this is the push to Octopus step:

![image](https://cloud.githubusercontent.com/assets/2734580/18451612/98d2b738-792f-11e6-843c-9fac95320b7a.png)

My artifacts are uploaded to VSTS:

![image](https://cloud.githubusercontent.com/assets/2734580/18451678/d1764ec4-792f-11e6-8b14-207290b16313.png)

But the push to Octopus step fails:

```
2016-09-12T20:21:22.4020703Z ##[command]"C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.104.1\tasks\OctopusPush\1.2.59\Octo.exe" push --server=https://octopus.***.net/ --apiKey=******** 
2016-09-12T20:21:22.4970689Z Octopus Deploy Command Line Tool, version 3.4.2+Branch.master.Sha.869d64eaf5d2657a5daadda886a2dd697e2a024c
2016-09-12T20:21:22.7250699Z Handshaking with Octopus server: https://octopus.***.net/
2016-09-12T20:21:27.6956844Z Handshake successful. Octopus version: 3.3.27; API version: 3.0.0
2016-09-12T20:21:27.8461316Z Authenticated as: ******** <""> "(a service account)"
2016-09-12T20:21:27.8461316Z Please specify a package to push
2016-09-12T20:21:27.8471313Z Exit code: -1
2016-09-12T20:21:28.1451318Z ##[error]Process 'Octo.exe' exited with code '-1'.
```

Does my setup look ok, or do you think there is an issue with the VSTS task?

**Comment by kevinkuszyk** [comment]
Ping @Dalmirog.  Any update in this?

**Comment by Damovisa** [comment]
Hi @kevinkuszyk,

Apologies for the delay in replying to this issue. It has been fixed and it seems to work correctly for me. Please reopen if it's still failing!

**Comment by kevinkuszyk** [comment]
Thanks @Damovisa.  It's been a while since I worked on the project that used this.  I should be doing some more on it in the new year.  I'll let you know if I have any more issues with it.
