### ISSUE TITLE
TFS vNext Build Fails with Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available

### ISSUE THREAD

**Issue by johnkattenhorn** [OctopusDeploy/OctoTFS#6]
Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or 

Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again. 

I've tried adding the -UseBasicParsing into the script too but I then get a bunch of different errors. But this might be related to the other Issue I've logged.

**Comment by johnkattenhorn** [comment]
I have an incorrect project-id which I've corrected and now I get the following error:

    "{{\r\n    \"Version\":  null,\r\n    \"SelectedPackages\":  [\r\n                             {{\r\n                                 \"Version\":  \"0.2.0-unstable0023\",\r\n                                 \"StepName\":  \"Deploy Argentiere.Compliance.Web\"\r\n                             }}\r\n                         ],\r\n    \"ProjectId\":  \"Projects-40\"\r\n}}"

    Invoke-WebRequest : The remote server returned an error: (400) Bad Request.
    At C:\a\21fb3270\Argentiere\build\CreateOctopusRelease.ps1:101 char:13

Could this be because I'm running against v3 of Octopus ?

**Comment by shlomcoh** [comment]
did anyone solved this issue? I added  -UseBasicParsing  and it works itermitante.
anyone has a stable solution?

**Comment by lkjangir** [comment]
For me, it is not working with -UseBasicParsing option as well.

**Comment by alltej** [comment]
I have this same issue as well.
