### ISSUE TITLE
Don't push packages for `refs/pull/*/merge` branches

### ISSUE THREAD

**Issue by nshenoy** [OctopusDeploy/OctoTFS#69]
Since there are no conditional build tasks in VSTS yet, it would be great to have a check in the Octopus-Push task that will effectively noop if it detects that it is being executed on a build from a `refs/pull/*/merge` branch. This will allow people to reuse a single build definition for CI builds and have their pull request branch policy for `master` (or whatever) set to use this same CI build def.

**Comment by Daniel-Svensson** [comment]
It seems like VSTS and TFS now support conditional execution which could solve the issue but it seems like the current version of the build tasks dont support that feature

**Comment by nshenoy** [comment]
Conditional build tasks are available as a preview feature in VSTS. You'll need to enable it for your organization. The conditionals work great for this purpose. We've been using this preview feature for several weeks now and it's been fantastic.

**Comment by Daniel-Svensson** [comment]
@nshenoy do you se conditional task for octopus targets, tried it in TFS 2107 update 2 RC1 and most targets have conditional execution but not the octopus build targets. Som other build tasks seems to require using a never version of it to get the conditional execution option, or maybe there is some logic which disables it for TFS?

**Comment by nshenoy** [comment]
Cool, glad you found it in VSTS! Hopefully they'll update TFS onprem soon with this feature. We're using it all over the place. ;)
