### ISSUE TITLE
Octopus-Push.ps1 only pushes first file

### ISSUE THREAD

**Issue by roryprimrose** [OctopusDeploy/OctoTFS#72]
I am using ```$(Build.SourcesDirectory)\**\bin\**\*.nupkg``` to identify the packages to upload. I'm expecting the following packages to be matched to this filespec:

- Product.Database\bin\release\Product.Database.X.Y.Z.nupkg
- Product.Portal\bin\release\Product.Portal.X.Y.Z.nupkg
- Product.Portal.Offline\bin\release\Product.Portal.Offline.X.Y.Z.nupkg

Version 2 of the Octopus push build step only finds and pushes the first package. I've tried to re-produce this locally and I don't get any files resolved. Regardless, I think the issue is that Get-Item is used instead of Get-ChildItem. Get-Item only looks at a specified location and doesn't handle recursion. See https://github.com/OctopusDeploy/OctoTFS/blob/master/source/VSTSExtensions/OctopusBuildAndReleaseTasks/Tasks/Push/Octopus-Push.ps1#L27

This line should be changed to

```
foreach ($file in (Get-ChildItem -Path $Package -Recurse)){
```

**Comment by roryprimrose** [comment]
@Damovisa Thanks for the merge. Any idea when this patch will be available in VSTS?

**Comment by Damovisa** [comment]
@roryprimrose I'll push it today :)  I just need to do another small update to the documentation.

**Comment by roryprimrose** [comment]
Thanks @Damovisa. From memory the v2 of this task was already in VSTS prior to this fix being merged. This is the only version we currently see against our account. Will this fix be under v3 of the task? Does this get automatically sync'ed into VSTS?

It would be handy if the git releases/tags identified what was in the releases. This would be helpful for us to determine which version of the task we want to use.

Cheers

**Comment by roryprimrose** [comment]
@Damovisa We still see v2 of this task in VSTS and the marketplace. We have ongoing issues with pushing packages to our OD server that this step would resolve. Is there any indication when this patch will be available on the marketplace?
