### ISSUE TITLE
Validate Octopus URL for common mistakes

### ISSUE THREAD

**Issue by Dalmirog-zz** [OctopusDeploy/OctoTFS#83]
We often get tickets from users that get `404`s in their `Octo.exe` calls because they registered they URL like `http://Octopus/app#/` or `http://octopus/api/` instead of using the base URL `http://Octopus`. This is a very common and understandable mistake and unfortunately the dialog box where you register the connection endpoint in TFS/VSTS doesn't allow us validate the user input before they save it.

So as a workaround, we could validate the URL in our build scripts.

**Comment by Dalmirog** [comment]
One of the many sources: https://help.octopusdeploy.com/discussions/problems/58078-unable-to-push-packages

**Comment by Dalmirog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [jh](https://trello.com/c/vK6HBM3Q/315-jh)
