### ISSUE TITLE
Create Release link broken (404) with Octopus 4.0

### ISSUE THREAD

**Issue by MarcusFelling** [OctopusDeploy/OctoTFS#85]
The link that is created on the build results page returns 404 after upgrading to 4.0.
**Example:** http://$InstanceName/octopus/app#/%2Freleases%2FReleases-10402
Looks like the new URL for releases is http://$InstanceName/octopus/app#/projects/$ProjectName/releases/$ReleaseName
![brokenlink](https://user-images.githubusercontent.com/6855361/32994873-475818b4-cd32-11e7-899a-c1de9784ca8d.PNG)

**Comment by markryd** [comment]
Thanks for raising this @MarcusFelling. Our goal with 4.0 was to make sure all links still worked, so I'm going to close this and have created an issue on our main public Issues list to fix things in Octopus itself here: https://github.com/OctopusDeploy/Issues/issues/3935
