### ISSUE TITLE
Add ability to use an Internal octopus deploy server with VSTS

### ISSUE THREAD

**Issue by mackayj** [OctopusDeploy/OctoTFS#86]
Right now octopus deploy must be public facing so VSTS can talk to it to get the server config. We use an internal octopus deploy since we only do internal projects. With our internal TFS server this is no issue, but we are trying to move to VSTS and are now having to manually call octo which runs on our internal build machine. It would be great to have support (version dropdown menu like some scripts?) to just type in our variables like project name / environment so we could still publish using the UI and not from command line.

Old config:

Internal TFS, Internal Build Server, Internal Octopus

Newer config:

VSTS, Internal Build Server, Internal Octopus

There are a lot of nice features the UI / Existing tasks provide like release notes and other features, we'd like to keep those, but have the ability to manually type in the project name and other variables.

Thanks!

**Comment by thebigmoosey** [comment]
Hi,

Thanks for getting in touch.

We're not sure we understand your setup and are hoping your can clarify some things. In your newer config, is VSTS acting as your build server, or only as your source control?

We're not sure how we could add a feature for internal OD servers to be seen by an external tool like VSTS. In cases like this, would you be able to add a firewall rule/exception that allows VSTS to see Octopus directly as a VSTS service endpoint?

In future, would you be able to contact us via one of our [support system(s)](https://octopus.com/support) please (see the "Ask" section), as these GitHub repositories are not necessarily monitored by support and may get lost/forgotten, so email or the forums are your best bet for reporting bugs or feature requests for any of our systems :)

Cheers
Mark

**Comment by mackayj** [comment]
@thebigmoosey Thanks for the response :)

We are just using VSTS for source control, our build server is still our internal one which can talk with our internal octopus deploy server just fine, but we can't use the tasks you guys created since that requires VSTS talking directly with Octopus. The old tasks used to allow you to manually type in the project anem and such, but the new ones use API calls to fill out a dropdown list, which doesn't work since VSTS can't talk with our Octopus Deploy server. If we had the option to still manually fill out the task info that would be awesome :)

**Comment by mackayj** [comment]
@thebigmoosey I also added it to the support section here: https://help.octopusdeploy.com/discussions/questions/15855-vsts-tasks-require-public-octopus-deploy-server

**Comment by thebigmoosey** [comment]
Closing, as this has been moved to support.
