### ISSUE TITLE
Issue with VSTS push package

### ISSUE THREAD

**Issue by bova80** [OctopusDeploy/OctoTFS#88]
https://github.com/OctopusDeploy/OctoTFS/blob/e0a666b7ffd321916f9ea611adf7ddeaa9a336dd/source/VSTSExtensions/OctopusBuildAndReleaseTasks/Tasks/Push/Octopus-Push.ps1#L27

the -recurse when looking for a package to push is causing an issue where even if you specify a folder it will looker farther in for the file.  brought this to attention on Octopus User Group slack channel: https://octopususergroup.slack.com/archives/C6UEBB7R9/p1512078761000242

**Comment by slewis74** [comment]
This is working as expected. 

It can cause an issue if you have your output directory set to a parent folder of your `obj\octopacked` folder, which OctoPack uses to build the package and then copy it to the output directory. In which case your package will get picked up twice.

We'd recommend using a folder, e.g. something like `artifacts`, off the parent folder to prevent this double up. This also prevents you from potentially scanning/recursing through every file in your source tree, as there will usually be only a few files/folders produced as artifacts of your build (certainly when compared to how many are in your source tree).
