### ISSUE TITLE
VSTS Commit Messages are truncated

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/OctoTFS#89]
This issue was created in response to https://help.octopusdeploy.com/discussions/problems/68173.

Ticking `Include Changeset Comments` in the create release step will include the title and description of a PR, but the text is truncated.

**Comment by mcasperson** [comment]
From my testing the title and description combined are limited to 100 characters. So a 100 character PR title would not have any description shown.

**Comment by mcasperson** [comment]
This is an example of the response when title and description is truncated. Note the `"messageTruncated":true` field.

{
   "count":3,
   "value":[
      {
         "id":"b0683f44b629dfc31c1b1b40c2f59cfcffe8b8f4",
         "message":"Merged PR 2: Merge message-change to master\n\ndescription 1234567890123456789012345678901234567890123",
         "type":"TfsGit",
         "author":{
            "id":null,
            "displayName":"devops",
            "uniqueName":"devops@octopus.com"
         },
         "timestamp":"2018-01-25T02:59:53Z",
         "location":"https://octopus-deploy-test.visualstudio.com/DefaultCollection/_apis/git/repositories/3e24dba9-7433-4f1e-a472-54cf3a05f129/commits/b0683f44b629dfc31c1b1b40c2f59cfcffe8b8f4",
         "messageTruncated":true,
         "pusher":"816d2d3a-5bfa-4cb7-be47-174d36e02df0"
      },
      {
         "id":"84c39af6b632f1a92bc37af93532cc0d7b708123",
         "message":"Still working with commit messages.",
         "type":"TfsGit",
         "author":{
            "id":null,
            "displayName":"Matthew Casperson",
            "uniqueName":"matthewcasperson@gmail.com"
         },
         "timestamp":"2018-01-25T02:58:52Z",
         "location":"https://octopus-deploy-test.visualstudio.com/DefaultCollection/_apis/git/repositories/3e24dba9-7433-4f1e-a472-54cf3a05f129/commits/84c39af6b632f1a92bc37af93532cc0d7b708123",
         "pusher":"816d2d3a-5bfa-4cb7-be47-174d36e02df0"
      },
      {
         "id":"fb72dc012f55d34221fa24705e686f0ad747ae37",
         "message":"Still working with commit messages. 1234567890123456789012345678901234567890123456789012345678901234",
         "type":"TfsGit",
         "author":{
            "id":null,
            "displayName":"Matthew Casperson",
            "uniqueName":"matthewcasperson@gmail.com"
         },
         "timestamp":"2018-01-25T02:58:20Z",
         "location":"https://octopus-deploy-test.visualstudio.com/DefaultCollection/_apis/git/repositories/3e24dba9-7433-4f1e-a472-54cf3a05f129/commits/fb72dc012f55d34221fa24705e686f0ad747ae37",
         "messageTruncated":true,
         "pusher":"816d2d3a-5bfa-4cb7-be47-174d36e02df0"
      }
   ]
}

**Comment by mcasperson** [comment]
This 100 character limit would appear to be hard coded by the VSTS API - https://social.msdn.microsoft.com/Forums/en-US/587cedd4-ed32-421a-9aaf-4040c77ce1f5/tfs-git-api-commits-maxcommentlength-limited-to-100-chars-in-the-comments-today?forum=tfsgeneral

There is a user voice post to remove this restriction at https://visualstudio.uservoice.com/forums/330519-team-services/suggestions/16950181-using-tfs-git-rest-api-to-get-commits-the-comment

**Comment by DavidDeSloovere** [comment]
@mcasperson If you follow the location link (which gets the actual commits instead of the changes on the build), will you get the full description there? I believe I saw this yesterday, but maybe my messsages weren't long enough for this second endpoint.

` "location":"https://octopus-deploy-test.visualstudio.com/DefaultCollection/_apis/git/repositories/3e24dba9-7433-4f1e-a472-54cf3a05f129/commits/fb72dc012f55d34221fa24705e686f0ad747ae37",`

**Comment by mcasperson** [comment]
This is resolved in 2.0.95 of the TFS plugin.
