### ISSUE TITLE
Links are created to the wrong repository

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/OctoTFS#96]
From https://help.octopus.com/t/vsts-create-release-step-fails-if-release-notes-from-changelog-comments-is-enabled/20909:

> Our source code is in Github, but the generated links seem to assume that the source is in VSTS-hosted git - i.e. the url is https://(mycompany).visualstudio.com/(some-guid)/_git/(project)/commit/(sha1) instead of https://github.com/(mycompany)/(project)/commit/(sha1) 1

**Comment by mcasperson** [comment]
Also https://help.octopus.com/t/azuredevops-create-octopus-release-assuming-source-is-in-tfs/21527.

**Comment by redwyre** [comment]
I think while these are related the actual reason for my

> Also https://help.octopus.com/t/azuredevops-create-octopus-release-assuming-source-is-in-tfs/21527.

While this is generally related to the previous issue, it is caused by this change: https://github.com/OctopusDeploy/OctoTFS/pull/90/commits/eaa84d7d5d5acc0d523c8eb73e3359470784af72#diff-d3cac3960ccefe1f07827eb8e43871adR20

**Comment by mcasperson** [comment]
Links are no longer generated when the source repo is not hosted by TFS.

@redwyre Version 3 of the plugin does not make the additional calls, so if you upgrade the issue should be resolved for you.
